- conf/nginx/symfony4.conf.erb
- frameworks/symfony
> Add symfony 4 support

- conf/nginx/codeigniter.conf.erb
- conf/nginx/wordpress.conf.erb
- frameworks/codeigniter
Related to Scalingo/documentation#399
> Add CodeIgniter support

- support/ext/mongodb
Update the MongoDB driver so that it support MongoDB 4 new feature.
Fix #70
> [MongoDB driver] Update to 1.5.3

- bin/compile
> Fix WEB_CONCURRENCY conflict with node.js buildpack

- bin/compile
> Add APP_ENV to prod by default

- support/ext/redis
> Update PHP Redis from 3.1.4 to 4.3.0

- bin/compile
> Loop through env variables which works for multi-line var

- bin/compile
Fix #107
I tested with:
- scalingo-14 and PHP 7.3
- scalingo-18:
- PHP 7.3
- PHP 7.4
> Lib oniguruma is only for PHP 7.4 and above

- bin/compile
- support/package_php
It works: https://test-php-74.osc-fr1.scalingo.io/
Fix #109
> Correctly compile PHP 7.4 with GD support

- support/ext/mongodb
Related to https://github.com/mongodb/mongo-php-driver/releases/tag/1.6.1
> [MongoDB Driver] Release 1.6.1

- support/package_nginx
Related to https://github.com/Scalingo/nginx-buildpack/issues/10
> Better explanation of the package_nginx script

- support/package_php
> Only download libonig if stack is not scalingo-14

- bin/compile
- conf/nginx/symfony4.conf.erb
- frameworks/symfony
- `APP_ENV` is needed during the build otherwise the deployment fails with:
```
[...]
- Installing symfony/yaml (v5.0.2): Loading from cache                                                                                                                                      
Generating optimized autoload files                                                                                                                                                           
ocramius/package-versions: Generating version class...                                                                                                                                 
ocramius/package-versions: ...done generating version class …
```
> [Symfony 5] Define APP_ENV during the build

- README.md
Related to https://github.com/Scalingo/documentation/issues/800
> [PHP + Node.js] Better explain the default Node.js support in PHP buildpack

- support/ext/mongodb
> [MongoDB Driver] Release 1.7.1

- CONTRIBUTING.md
- README.md
- conf/buildpack.conf
Related to https://github.com/Scalingo/appsdeck-kitchen/issues/705
> Fix OVH cloud storage URL

- bin/compile
> set APP_ENV=prod by default in profile.d/php.sh for symfony apps

- support/get_libc_client
Related https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/26132321774
Already pushed to object storage for stack scalingo-18
No need for scalingo-14
> Update version of IMAP client used for php-imap

- support/ext-internal/gettext
> fix #143, gettext extension support

- bin/compile
- lib/newrelic
Tested here: https://my.osc-fr1.scalingo.com/apps/biniou/deployments/c7d723f2-cf82-46b7-9f92-65b8935f9ab9
Fix #150
> [New Relic] Default version from 9.3.0.248 to 9.9.0.260

- bin/compile
- conf/php/newrelic.ini
No more error logs in this application: https://my.osc-fr1.scalingo.com/apps/biniou/logs
Fix #149
> [New Relic] Logs location is in /app/vendor/newrelic/*.log

- lib/nodejs
Fix #153
Time spent:
- Analysis: 1h30 (because i thought it was an issue on the nodejs buidlpack (facepalm))
- Fix: 5mn
> Follow redirects on node downloads

- support/package_php
Related to https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/12375700005569
> compile PHP with argon2 password hashing algorithms

- .gitignore
- bin/common.sh
- bin/compile
- support/package_reader
- support/reader/main.go
> [Logs] Use symbolic links to stdout instead of files

- support/reader/cmd/test-writer/writer.go
- support/reader/main.go
https://stackoverflow.com/questions/45443414/read-continuously-from-a-named-pipe
> Log tailing: sleep on EOF of io.Copy

- support/ext/mongodb
> [MongoDB Driver] Release 1.8.1

- support/ext/mongodb
> [MongoDB] Update from 1.8.1 to 1.8.2

- bin/compile
- conf/buildpack.conf
- support/ext/apcu
- support/ext/blackfire
- support/ext/event
- support/ext/igbinary
- support/ext/lua
- support/ext/mcrypt
- support/ext/memcached
- support/ext/mongodb
- support/ext/redis
Some extensions are not ready yet ext-internal/gmp ext/ds ext/phalcon ext/lua
Related to https://github.com/Scalingo/php-buildpack/issues/182 / [OPSB-187]
[OPSB-187]: https://scalingo.atlassian.net/browse/OPSB-187
> [OPSB-187] Add compatibility with PHP 8

- CONTRIBUTING.md
- README.md
- conf/buildpack.conf
> fix(swift): Switch to the Graveline region

- bin/compile
Related to
https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/61488/conversations/12375700034122
> sre(jq-dl) Ensure download is retried 3 times when downloading in bin/compile

- support/package_nginx
Related to https://github.com/Scalingo/nginx-buildpack/issues/22
> feat(nginx): compile with http_auth_request_module

- support/ext/mongodb
> chore(mongodb): update extension from 1.9.0 to 1.10.0

- conf/buildpack.conf
- support/ext-internal/gmp
- support/get_gmp
- support/get_sodium
- support/get_webp
- support/package_nginx
> chore: update third party libs

- README.md
- bin/compile
- lib/scout
Hello,
This PR enables support to install the [Scout APM](https://scoutapm.com/) extension.
> feat(scout): add support for ScoutAPM extension

- support/ext/imagick
> feat(imagick): upgrade from 3.5.1 to 3.7.0

- support/ext/blackfire
> fix(blackfire): support for PHP 8.1

- support/ext/mongodb
Fix #259
I will also release 1.12.1
> chore(php): Update mongodb from 1.11.1 to 1.13.0

- conf/buildpack.conf
- support/ext/igbinary
Upgrade the igbinary extension to version 3.2.7
Fixes #233
> fix(php-buildpack): upgrade igbinary extension to 3.2.7

- conf/buildpack.conf
- lib/composer
- support/ext/amqp
Add support for AMQP extension.
> feat(php-buildpack): add AMQP extension

- support/ext/redis
> chore(redis): update from 5.3.4 to 5.3.7

- support/ext/apcu
> chore(apcu): update from 5.1.21 to 5.1.22

- support/ext/mongodb
Update MongoDB extension to 1.14.2.
First step to fix #261.
> chore(mongodb): update to 1.14.2

- conf/buildpack.conf
> chore(igbinary): update from to 3.2.12

- conf/buildpack.conf
First step for the release of PHP 8.2.
Related to #280
> feat: php 8.2 release

- support/ext/mongodb
> chore(mongodb): update to 1.15.0

- conf/buildpack.conf
> chore(igbinary): update from 3.2.12 to 3.2.13

- lib/composer
Tested with success.
Fixes #319
> fix(composer): put the compiled PECL extensions in CACHE_DIR

- support/ext/mongodb
> chore(mongodb): upgrade to 1.15.3

- support/ext/mongodb
> chore(mongodb): update to 1.16.0

- support/ext/mongodb
> chore(mongodb): update to 1.16.1

- support/ext/mongodb
> chore(mongodb): update from 1.16.1 to 1.16.2

- conf/buildpack.conf
- support/package_php
> fix(zlib): upgrade to zlib 1.3

- support/ext/mongodb
> chore(mongodb): update from 1.16.2 to 1.17.0

- support/ext/apcu
> chore(apcu): update from 5.1.22 to 5.1.23

- conf/buildpack.conf
> chore(igbinary): update from 3.2.14 to 3.2.15

- conf/buildpack.conf
- support/ext/mongodb
> chore(mongodb): update from 1.17.0 to 1.17.1

- README.md
- bin/compile
https://pecl.php.net/package/scoutapm
> feat(scoutapm): upgrade default version from 1.7.0 to 1.10.0

- bin/compile
- lib/newrelic
Allows user to customize their New Relic deployment.
Successfully tested by the requesting customer.
> feat(newrelic): user can provide their own config

- conf/buildpack.conf
> chore(mongodb): update from 1.17.1 to 1.17.2

- bin/compile
> feat: update default New Relic agent version to 10.15.0.4

- conf/buildpack.conf
> chore(mongodb): update from 1.17.2 to 1.17.3

- conf/buildpack.conf
> chore(mongodb): update from 1.17.3 to 1.18.0

- conf/buildpack.conf
> chore(mongodb): update from 1.18.0 to 1.18.1.

- conf/buildpack.conf
> chore(mongodb): update mongodb 1.18.1 to 1.19.0

- conf/buildpack.conf
> chore(sodium): update libsodium to 1.0.20

- test/tests
> fix(tests): update nginx default version

- conf/buildpack.conf
Files have been uploaded to ObjectStorage.
Fix #443
> feat(zlib): update zlib to 1.3.1

- conf/buildpack.conf
> feat: release of MongoDB PHP extension 1.19.3

- conf/buildpack.conf
> chore(php-buildpack): update MongoDB extension from 1.19.3 to 1.19.4

- test/tests
> fix(tests): fix default Composer version

- bin/compile
- conf/buildpack.conf
> feat(php): release of PHP 8.4

- lib/nodejs
> fix(nodejs): download Node.js from official URLs

- conf/buildpack.conf
- support/get_gmp
- support/get_libonig
- support/get_sodium
- support/get_tidy
- support/get_webp
- support/get_zip
- support/get_zlib
- support/lib/swift
Fixing linter offenses I noticed in the scripts used in the context of scalingo-24 work
> refactor: linter offenses

- conf/buildpack.conf
- support/get_webp
I also added https://github.com/webmproject/libwebp to the list of releases we monitor.
I uploaded the lib for scalingo-20, scalingo-22 and scalingo-24.
> feat(webp): update to 1.6.0
