Scalingo/php-buildpack

conf/nginx/base.conf.erb
conf/php/php.ini

Set PHP max upload size to 70m, accordingly to Scalingo routers

---

README.md
support/ext-internal/ftp
support/package_php

Fix #47
Cf. phpinfo here: https://php7-support.scalingo.io/
In the section "Module Authors", there is a credit for the FTP module which was not present before the patch.

Add FTP support

---

bin/compile

* `composer.json` can now have these keys: `.require.php`,
`.config.platform.php`, `.extra.paas.engines.php`, in this order of priority.
This ensure the retrocompatibility + accept what seems to be a standard
from the community:
References:
* https://getcomposer.org/doc/06-config.md
* https://andy-carter.com/blog/composer-php-platform
* http://syrwebdev.com/composer/2015/01/07/using-composer-to-require-php-modules.html

Improve PHP version detection and switch to 7.2 as a default

---

conf/php/php-fpm.conf

Define start_servers to avoid warning when php-fpm is starting

---

bin/compile
conf/php/php-fpm-73.conf

It has been fixed in PHP 7.3: https://github.com/php/php-src/pull/2458
With a custom php-fpm parameter: `decorate_workers_output`

Fix dirty logging on stdout/stderr (WARNING child with PID said on stderr)

---

support/ext/phalcon

Version 3.4.3 is deployed
Available for PHP 7.0, 7.1, 7.2, 7.3
https://github.com/phalcon/cphalcon
https://phalconphp.com/en/
To install it:
```
{
"require": {
"ext-phalcon": "*"
}
}
```

Add support for extension Phalcon

---

conf/nginx/phalcon.conf.erb
frameworks/phalcon

https://sample-php-phalcon.scalingo.io
```
└> git push scalingo master
Enumerating objects: 27, done.
Counting objects: 100% (27/27), done.
Delta compression using up to 4 threads
Compressing objects: 100% (25/25), done.
Writing objects: 100% (27/27), 485.03 KiB | 3.88 MiB/s, done.
Total 27 (delta 0), reused 0 (delta 0)
<-- Start deployment of sample-php-phalcon -->
-----> Cloning custom buildpack: https://github.com/Scalingo/php-buildpack#feature/phalcon-framework
-----> Bundling NGINX 1.15.8
-----> Bundling PHP 7.2.15
-----> Bundling extensions
apcu
phpredis
mongodb
mcrypt
-----> Vendoring Composer
Updating Composer
-----> Bundling additional extensions phalcon
phalcon
Updating to version 1.8.4 (stable channel).
Downloading (100%)
Use composer self-update --rollback …
```

After supporting phalcon module, support phalcon framework

---

support/ext/memcached

This version is mandatory for the support of PHP 7.3.
What needs to be done to update memcached version? Anything else than this
modification?

Update to memcached 3.1.3

---

.gitmodules
conf/buildpack.conf
support/get_zip
support/lib/swift
support/manifest
support/package-checksum
support/package_composer
support/package_nginx
support/package_php

Of course, retrocompatible with scalingo, assets of the legacy stack have been migrated, to the `scalingo/` namespace on the object storage

Compatibility with scalingo-18

---

support/ext/mongodb

https://github.com/mongodb/mongo-php-driver/releases/tag/1.6.0

Update MongoDB driver to 1.6.0

---

lib/composer
support/lib/output
support/manifest

Close #111 
Preview:
```bash
<-- Start deployment of php-buildpack-test -->
Fetching deployment cache
-----> Cloning custom buildpack: https://github.com/Scalingo/php-buildpack#fix/111/output-enhancement
-----> Bundling NGINX 1.15.8
Checksums match. Fetching from cache.
-----> Bundling PHP 7.4.0
Checksums match. Fetching from cache.
-----> Bundling extensions
apcu
Checksums match. Fetching from cache.
phpredis
Checksums match. Fetching from cache.
mongodb
Checksums match. Fetching from cache.
-----> Vendoring Composer
-----> Bundling additional extensions: curl json libxml mbstring openssl simplexml 
curl
Checksums match. Fetching from cache.
json
Checksums match. Fetching from cache.
libxml
Checksums match. Fetching from cache.
mbstring
Checksums match. Fetching from …
```

Fix output for additional extensions

---

bin/compile

The default Nginx with the current buildpack is `1.15.8` as reported by the user in the related issue. With this version of the buildpack:
```
<-- Start deployment of etienne-default-nginx -->
-----> Cloning custom buildpack: https://github.com/Scalingo/php-buildpack.git#fix/120/default_nginx
-----> Bundling NGINX 1.16.1
-----> Bundling PHP 7.4.1
[...]
```
1.16.1 is the default returned by semver (http://semver.scalingo.io/nginx-scalingo-18/). ~I need to find how to configure semver to return 1.17.6 as the new default.~ Actually 1.16.1 is the latest on the stable branch. It's probably best to use it as default, don't you think? 
With an unsupported version of Nginx:
```
<-- Start deployment of etienne-default-nginx -->
Fetching deployment cache …
```

Nginx and PHP versions from semver

---

bin/common.sh
bin/compile

```
└> scalingo -r oscalingo env-set BUILDPACK_URL=https://github.com/Scalingo/php-buildpack#feature/nginx-semver
gitBUILDPACK_URL has been set to 'https://github.com/Scalingo/php-buildpack#feature/nginx-semver'.
└> git push oscalingo master -f
Enumerating objects: 34, done.
Counting objects: 100% (34/34), done.
Delta compression using up to 4 threads
Compressing objects: 100% (29/29), done.
Writing objects: 100% (34/34), 6.58 KiB | 2.19 MiB/s, done.
Total 34 (delta 11), reused 0 (delta 0)
<-- Start deployment of sample-php-base -->
-----> Cloning custom buildpack: https://github.com/Scalingo/php-buildpack#feature/nginx-semver
-----> Bundling NGINX 1.18.0
-----> Bundling PHP 7.4.4
-----> Bundling extensions
apcu
...
<-- https://sample-php-base.osc-fr1.scalingo.io --> …
```

User 'nginx-<stack>' source in semver to define nginx version

---

bin/compile
conf/buildpack.conf
frameworks/phalcon
lib/composer
support/lib/swift
support/package_composer
support/package_nginx

Example of warning message:
```
╰─$ git push scalingo master --force
[...]
Your deployment has been queued and is going to start…
<-- Start deployment of test-php-buildpack -->
Fetching deployment cache
-----> Cloning custom buildpack: https://github.com/Scalingo/php-buildpack#fix/168/composer_version_configurable
######################################
WARNING: You are using Composer 1.10.16. Composer 1 is End of Life since the 24th of October 2020 and will soon be deprecated.
https://blog.packagist.com/composer-2-0-is-now-available/#4-what-s-next
######################################
-----> Bundling Nginx 1.18.0
[...]
-----> Vendoring Composer 1.10.16
Updating Composer
[...]
```
See the latest deployments of …

Make the Composer version configurable

---

bin/compile

Warning if license key is missing
```
2020-11-05 10:07:05.032877300 +0100 CET [manager] container [web-1] (5fa3c0aa987e0b2c03995458) started
2020-11-05 10:07:05.133446753 +0100 CET [web-1] !
2020-11-05 10:07:05.133474240 +0100 CET [web-1] ! New Relic agent has been installed but is misconfigured
2020-11-05 10:07:05.133486005 +0100 CET [web-1] ! NEW_RELIC_LICENSE_KEY should be define in the application environment
2020-11-05 10:07:05.133490749 +0100 CET [web-1] !
2020-11-05 10:07:05.133491857 +0100 CET [web-1] ! Documentation: https://doc.scalingo.com/languages/php/start
2020-11-05 10:07:05.133492612 +0100 CET [web-1] !
```

Ensure new relic logs are working all the time, not only when starting php-fpm (web containers)

---

frameworks/cakephp2
frameworks/change4
frameworks/drupal
frameworks/laravel
frameworks/lumen
frameworks/phalcon
frameworks/prestashop
frameworks/silex
frameworks/slim
frameworks/symfony
frameworks/yii
frameworks/yii2
frameworks/zf2

To fix this I've just used good practice for bash script: always using quotes and interpolating content in it when comparing to string

Correctly handle when composer.json includes: '.extra.paas.framework == ""', no more warning of unary operator

---

bin/compile

Tested in https://dashboard.scalingo.com/apps/osc-fr1/biniou/deploy/db1b2650-e373-47b4-9b26-575c856a0945
Fix #194

release(new-relic): default version from 9.16.0.295 to 9.17.1.301

---

conf/buildpack.conf
support/ext-internal/sodium
support/ext/mongodb
support/package_all
support/package_php

- ds and lua extensions don't work. lua was already broken for PHP 8.0.
- XML-RPC has moved to a PECL module. Hence it's now enabled in this release.
- For the scalingo-18 stack the libzip version included in the OS is not recent enough. Hence it is not supported. (`WARNING: Libzip >= 1.2.0 needed for encryption support`)
Fix #222
Fix #223
Fix #224

release(php): add support for PHP 8.1

---

support/ext/apcu

APCU changelog (https://github.com/krakjoe/apcu/releases/tag/v5.1.21):
> Fixed compatibility with PHP 8.1 by adding return types to `APCUIterator`.
Related to https://github.com/Scalingo/php-buildpack/issues/228

release(apcu): update from 5.1.20 to 5.1.21

---

support/ext/apfd

It has been compiled for scalingo-18 and scalingo-20, for all PHP versions (7.4, 8.0 and 8.1).
phpinfo example: https://biniou.osc-fr1.scalingo.io/#module_apfd
Fix #237

feat(ext): add apfd support

---

README.md
bin/compile
lib/datadog

Hi Scalingo,
This PR is my attempt to install [Datadog Application Security](https://docs.datadoghq.com/fr/security_platform/application_security/) extension, following the [install instructions](https://github.com/DataDog/dd-appsec-php).
---
**ORIGINAL POST** (2021-03-09):
It does not work right now and I am facing this issue:
```
-----> Installing Datadog Tracer and AppSec extension
sh: 1: ldconfig: not found
ERROR: Cannot find library 'libcurl'
Failed command (return code 1): ldconfig -p | grep libcurl
```
It looks like `ldconfig` is not available in the build, though I had no problem when testing locally with the [scalingo/scalingo-18](https://hub.docker.com/r/scalingo/scalingo-18) docker image :thinking: 
What's wrong with ldconfig?
---
**UPDATE** (2021-03-11):
:partying_face: It now …

feat(datadog): Install Datadog Tracer and Appsec extensions

---

bin/compile

9.21.0.311 adds support for PHP 8.1
Fix #239

fix(newrelic): upgrade from 9.17.1.301 to 9.21.0.311 by default

---

lib/nodejs

Fixes [SRE-682]
[SRE-682]: https://scalingo.atlassian.net/browse/SRE-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SRE-682] Use official S3 nodejs repository instead of legacy heroku.com URL

---

conf/buildpack.conf

Update igbinary extension to 3.2.9.
First step to fix #271.

chore(igbinary): update to 3.2.9

---

support/package_all

The `ds` and `lua` extensions are ignored starting with PHP 8.1.
(They don't compile)

fix: ignore ds and lua ext. with php 8.2

---

bin/compile

Should add support for PHP 8.2.
https://download.newrelic.com/php_agent/archive/10.4.0.316/

release(new-relic): upgrade default from 9.21.0.311 to 10.4.0.316

---

bin/compile
lib/composer
lib/pecl
lib/pecl_oci8

- Installation of `libaio` via the APT builpack
- Installation of the oracle client in the vendor folder
- Cache oracle client download and APT buildpack clone
- Warning raised at build time for `libaio` should be fixed
Fix #290

feat(oci8): support `oci8` extensions

---

README.md
bin/compile
lib/apt
lib/composer
lib/package
lib/pecl
lib/pecl_oci8

I went through the PECL download statistics (https://pecl.php.net/package-stats.php) and tested a bunch of the packages from there. The PHP info is here: https://biniou.osc-fr1.scalingo.io/. Some of these packages are really old so I didn't tested them. I tried to find some packages that are still maintained:
- Swoole (https://pecl.php.net/package/swoole): works easily
- YAML (https://pecl.php.net/package/yaml): also needs the APT buildpack to install `libyaml-dev`
- TimezoneDB (https://pecl.php.net/package/timezonedb): works easily
- amqp (https://pecl.php.net/package/amqp): also needs the APT buildpack to install `librabbitmq-dev`
Fix #249

feat(composer): install PECL extension

---

lib/composer

Fixes #297
`simplexml` extension is displayed as `SimpleXML` in embedded modules list

fix(php-ext-simplexml) Ignore case when checking embedded extensions since PHP module names are not consistent

---

support/ext/amqp

Extension has been compiled with `rabbitmq-c-0.13.0` for:
- `scalingo-20`: PHP `7.4`, `8.0`, `8.1` and `8.2`
- `scalingo-22`: PHP `8.1` and `8.2`
It's not compatible with `scalingo-18` (`cmake` version requirement can't be honored), hence some specific code kept until `scalingo-18` is fully deprecated.
Files have been uploaded to ObjectStorage.
Fixes #293

Fix/php buildpack/293/rabbitmq-c-0.13.0

---

support/get_libc_client

Make sure the `get_libc_client` script also works with `scalingo-22-minimal`.

fix(get_libc_client): ensure compatibility with scalingo-22-minimal stack

---

lib/composer

Related to https://github.com/Scalingo/php-buildpack/issues/325 
If the  `php --modules` command fails we raise an error containing the return code and the error message. We also stop the execution of the buildpack.

fix(modules) Handling the case when php module listing fails

---

lib/composer

Properly handle the `zend-opcache` extension.
Fixes #331

fix(php-buildpack): properly handle 'zend-opcache' extension

---

support/ext/mongodb

The usual `mongodb-$version.tgz` asset has not been uploaded on Github.
I suggest to change the URL to point to PECL, since the extension will always be available there.
This would allow to fix #344

fix(mongodb): update download URL

---

conf/buildpack.conf
support/get_sodium

Packages have been generated and uploaded on Object Storage for both `scalingo-20` and `scalingo-22`.
Fixes #352

chore(sodium): upgrade to 1.0.19

---

conf/buildpack.conf

Packages have been generated and uploaded on Object Storage for `scalingo-20`, `scalingo-22`, `scalingo-20-minimal` and `scalingo-22-minimal`.
Fixes https://github.com/Scalingo/php-buildpack/issues/354

chore(webp): upgrade to 1.3.2

---

README.md
lib/datadog

fixes https://github.com/Scalingo/php-buildpack/issues/350
This pull request changes the way Datadog extensions are installed:
- stop using the old install script that was in public beta (and did not officially support PHP 8.2)
- use the new install script provided by Datadog
- avoid failures due to Github API rate limits, as reported in https://github.com/Scalingo/php-buildpack/issues/350
- stop documenting how to request specific versions of the extensions: it has never worked, and the new install script does not support this feature.
I don't know if other people are using this feature, so I did my best to avoid a breaking change and kept the environment variables the same as before.
I have been testing this branch on our production project and it works just fine:
```
[LOG] -----> …
```

fix(datadog): Use the new Datadog installer

---

.github/workflows/ci.yml
Makefile
test/run
test/shunit2
test/tests

Add a few things required to include tests in a near future:
- a `Makefile` that allows to launch tests locally (`make test`)
- a GitHub Action that will run the tests when opening a Pull Request
- a `test/shunit2` file, which is the binary of shUnit2
- a `test/run` file to launch the tests
- a `test/tests` file that contains the tests.
Two dummy tests have been added:
- one that should pass,
- and one that should fail (and we'll have to fix it to pass the CI)

feat(test): add what's necessary for tests

---

Makefile

Add ability to run:
- `make test20` to run tests on the scalingo-20 stack.
- `make test22` to run tests on the scalingo-22 stack.
- `make all`: to run tests on both scalingo-20 and scalingo-22 stacks.
- `make` and `make test` default to `make all`.

feat(tests): improve Makefile

---

bin/compile
test/helpers
test/tests

Make sure choosing a PHP version with Composer always prevails over setting `$PHP_VERSION` env var.
Also split some `test::helpers` into several functions for better usage.
I'm not that inspired for the `test::composer::over_*` functions naming :disappointed: so feel free to suggest something else!
Fix #404

fix(php-buildpack): composer prevails over env

---

.github/workflows/ci.yml

Trigger CI workflow when a push event occurs on the master branch.
Related to the discussion here in #364.
Fix #364

fix: fix CI workflow

---

lib/composer
lib/pecl_oci8

This PR fixes the deployment issue:
```sh
[LOG] + curl --silent https://download.oracle.com/otn_software/linux/instantclient/instantclient-sdk-linuxx64.zip --output oraclesdk.zip                                                                                                       
[LOG] + unzip -q oraclesdk.zip -d /build/036626aa-77f8-4ace-8f20-29077f408b28/vendor/oracle-client/                                                                                                                                            
[LOG] replace /build/036626aa-77f8-4ace-8f20-29077f408b28/vendor/oracle-client/META-INF/MANIFEST.MF? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL                                                                                               
[LOG] (EOF or read error, treating as …
```

fix(oci8): unzip should replace existing file

---

lib/composer

Fix #441 
Tested on a test app: https://biniou.osc-fr1.scalingo.io/#module_pdo_sqlsrv
Deployment logs excerpt:
```
[...]
-----> Bundling additional extensions
Installing PECL extension pdo_sqlsrv version 5.12.0
Installing PECL extension sqlsrv version 5.12.0
-----> Installing application dependencies with Composer
[...]
```

fix(composer): match exactly the extension name

---

lib/composer

fix(php-buildpack): fix zend opcache extension support

---

lib/nodejs

I noticed this while investigating on a support ticket.
I tested on an application and I find it much nicer to read:
```
-----> Node.js app detected (package.json)
-----> Requested Node.js versions range: 20.15.x
-----> Resolved Node.js version: 20.15.1
-----> Downloading and installing Node.js
TIP: Use npm shrinkwrap to lock down dependency versions
-----> package.json unchanged since last build
-----> Restoring node_modules from cache
-----> Installing Node.js dependencies
npm warn config production Use `--omit=dev` instead.
up to date, audited 1 package in 374ms
found 0 vulnerabilities
-----> Pruning unused Node.js dependencies
up to date, audited 1 package in 276ms
found 0 vulnerabilities
-----> Caching node_modules for future builds
-----> Cleaning up node-gyp and npm artifacts …
```

docs(nodejs): update Node.js spelling in logs

---

conf/buildpack.conf
support/ext/memcached

fix(memcached): release of memcached extension 3.3.0

---

support/ext-internal/ftp

Tested with 8.1.33, 8.2.29 and 8.4.10
```sh
root@9ad486d4a55b:/# php --version
PHP 8.1.33 (cli) (built: Jul  3 2025 07:14:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.33, Copyright (c) Zend Technologies
with Zend OPcache v8.1.33, Copyright (c), by Zend Technologies
root@9ad486d4a55b:/# php -r 'ftp_ssl_connect();'
Fatal error: Uncaught ArgumentCountError: ftp_ssl_connect() expects at least 1 argument, 0 given in Command line code:1
Stack trace:
#0 Command line code(1): ftp_ssl_connect()
#1 {main}
thrown in Command line code on line 1
root@9ad486d4a55b:/# 
```
Fixes #512

feat(ext-ftp) add ftps support
